# Modeling for early warning sytem using RF, HGB and OLS

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier, IsolationForest, RandomForestClassifier
from sklearn.metrics import auc, precision_recall_curve, roc_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
master_telecom_df = pd.read_csv("C:\\Users\\user\\OneDrive\\Documents\\2026 AD\\SATNAC 2026\\demo\\master_aiops_telemetry.csv", sep=",", low_memory=False)

In [3]:
# lets add engineered features to the model

import pandas as pd
import numpy as np

def engineer_advanced_telecom_features(df):
    df = df.copy()
    
    # 1. Efficiency Ratios
    df['throughput_per_user'] = df['throughput_mbps'] / (df['active_users'] + 1)
    df['prb_per_user'] = df['prb_utilization_pct'] / (df['active_users'] + 1)
    
    # 2. Compound Friction
    df['network_friction'] = df['latency_ms'] * df['packet_loss_pct']
    df['e2e_bottleneck'] = df['prb_utilization_pct'] * df['link_utilization']
    
    # 3. Rolling Volatility (Jitter & Instability)
    df['latency_roll_std'] = df['latency_ms'].rolling(window=3).std().fillna(0)
    df['packet_loss_roll_std'] = df['packet_loss_pct'].rolling(window=3).std().fillna(0)
    
    # 4. Categorical One-Hot Encoding for Traffic Type & QoS
    df = pd.get_dummies(df, columns=['traffic_type', 'qos_priority'], drop_first=True)
    
    return df

# Apply to your master dataframe
master_telecom_df = engineer_advanced_telecom_features(master_telecom_df)

In [4]:
# lets slect the features and target variable for the model

#lets make sure everything is an int not 

feature_cols = [
    # 1. Raw Base Metrics
    "prb_utilization_pct",
    "latency_ms",
    "packet_loss_pct",
    "link_utilization",
    "reachability",
    "active_users",
    "throughput_mbps",
    # 2. RF Signal Health Metrics
    "rsrp_dbm",
    "rsrq_db",
    # 3. Engineered Ratios & Friction
    "throughput_per_user",
    "prb_per_user",
    "network_friction",
    "e2e_bottleneck",
    # 4. Rolling Volatility / Jitter
    "latency_roll_std",
    "packet_loss_roll_std",
    # 5. One-Hot Encoded Traffic Types
    "traffic_type_http",
    "traffic_type_video",
    "traffic_type_voip",
    # 6. One-Hot Encoded QoS Priorities
    "qos_priority_2.0",
    "qos_priority_3.0",
    "qos_priority_4.0",
    "qos_priority_5.0",
]
target_col = "anomaly_flag"

# Ensure all selected features are converted to numeric (turning stray text strings into NaN)
for col in feature_cols:
  if col in master_telecom_df.columns:
    master_telecom_df[col] = pd.to_numeric(
        master_telecom_df[col], errors="coerce"
    )

In [5]:
#select the X and y variables for the model
X_raw = master_telecom_df[feature_cols].fillna(0).values # replqes NAN with 0
y_raw = master_telecom_df[target_col].astype(int).values # convert all rows to integers (0/1)

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_raw, y_raw, test_size=0.2, random_state=42, stratify=y_raw # 80 train data, 20 test data
)
# scale the features using StandardScaler so that they have mean = 0 and variance =1 because some of the features have different scales and ranges. 
# This is important for many machine learning algorithms, especially those that rely on distance metrics or gradient-based optimization.
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# RF

In [6]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

# 1. Configuration (Update 'target_col' if your column name differs)
target_col = (
    'anomaly_flag'  # <--- Change this to your actual column name if different
)
horizon_steps = 1  # 1 hour ahead for hourly data

# 2. Copy and prepare data (ensure it's chronologically sorted by your timestamp column!)
# df = df.sort_values(by='timestamp_column_name').copy()
df_forecast = master_telecom_df.copy()

# Create Future Target (Will there be an anomaly 1 hour from now?)
df_forecast['target_future'] = df_forecast[target_col].shift(-horizon_steps)

# 3. Engineer Lag and Delta (Rate of Change) Features for Hourly Data
key_features = [
    # 1. Raw Base Metrics
        "prb_utilization_pct",
        "latency_ms",
        "packet_loss_pct",
        "link_utilization",
        "reachability",
        "active_users",
        "throughput_mbps",
        # 2. RF Signal Health Metrics
        "rsrp_dbm",
        "rsrq_db",
        # 3. Engineered Ratios & Friction
        "throughput_per_user",
        "prb_per_user",
        "network_friction",
        "e2e_bottleneck",
        # 4. Rolling Volatility / Jitter
        "latency_roll_std",
        "packet_loss_roll_std",
        # 5. One-Hot Encoded Traffic Types
        "traffic_type_http",
        "traffic_type_video",
        "traffic_type_voip",
        # 6. One-Hot Encoded QoS Priorities
        "qos_priority_2.0",
        "qos_priority_3.0",
        "qos_priority_4.0",
        "qos_priority_5.0",
]
for col in key_features:
  if col in df_forecast.columns:
    # State of the network 1 hour ago
    df_forecast[f'{col}_lag_1h'] = df_forecast[col].shift(1)
    # Rate of change over the last hour
    df_forecast[f'{col}_delta_1h'] = (
        df_forecast[col] - df_forecast[f'{col}_lag_1h']
    )
    # 24-hour lag to capture daily seasonality (same hour yesterday)
    df_forecast[f'{col}_lag_24h'] = df_forecast[col].shift(24)

# Drop rows with NaNs resulting from shifts
df_forecast = df_forecast.dropna().reset_index(drop=True)

# 4. Separate Features (X) and Target (y)
exclude_cols = [target_col, 'target_future', 'timestamp', 'time']
feature_cols_forecast = [
    c for c in df_forecast.columns if c not in exclude_cols
]

X = df_forecast[feature_cols_forecast]

# CRITICAL FIX: Drop any remaining string/object columns (like cell IDs: 'CELL_019')
X = X.select_dtypes(include=[np.number])

y = df_forecast['target_future'].astype(int)

# 5. STRICT CHRONOLOGICAL SPLIT (Past trains, Future tests)
split_idx = int(len(df_forecast) * 0.8)
X_train_f, X_test_f = X.iloc[:split_idx], X.iloc[split_idx:]
y_train_f, y_test_f = y.iloc[:split_idx], y.iloc[split_idx:]

print(
    f'Training samples: {len(X_train_f)} | Test samples: {len(X_test_f)}'
)
print(f'Future anomalies in test set: {y_test_f.sum()}')

# 6. Train Random Forest with class weighting to handle rare events
rf_forecast = RandomForestClassifier(
    n_estimators=200, max_depth=12, random_state=42, class_weight='balanced'
)
rf_forecast.fit(X_train_f, y_train_f)

# Predict future probabilities
rf_probs_test = rf_forecast.predict_proba(X_test_f)[:, 1]


# 7. Find Optimal Threshold for F1-Score
def find_optimal_threshold(y_true, y_scores):
  thresholds = np.linspace(0.01, 0.99, 200)
  best_thresh = 0.5
  best_f1 = 0
  for t in thresholds:
    preds = (y_scores >= t).astype(int)
    score = f1_score(y_true, preds, zero_division=0)
    if score > best_f1:
      best_f1 = score
      best_thresh = t
  return best_thresh, best_f1


rf_threshold, best_rf_f1 = find_optimal_threshold(y_test_f, rf_probs_test)
print(f'\nRandom Forest 1-Hour Ahead Optimal Threshold: {rf_threshold:.3f}')

# Apply tuned threshold
final_rf_preds = (rf_probs_test >= rf_threshold).astype(int)

# 8. Evaluation Metrics
print('\n--- Random Forest 1-Hour Ahead Evaluation ---')
print(
    f'Precision: {precision_score(y_test_f, final_rf_preds, zero_division=0):.4f}'
)
print(f'Recall:    {recall_score(y_test_f, final_rf_preds, zero_division=0):.4f}')
print(f'F1-Score:  {f1_score(y_test_f, final_rf_preds, zero_division=0):.4f}')
print(f'ROC-AUC:   {roc_auc_score(y_test_f, rf_probs_test):.4f}')

# 9. Feature Importance Breakdown (Fixed)
importance_df = pd.DataFrame({
    'Feature': X_train_f.columns,  # Match the exact columns trained on
    'Importance': rf_forecast.feature_importances_,
}).sort_values(by='Importance', ascending=False)

print('\n--- Top 10 Predictive Features for 1-Hour Ahead Forecasting ---')
print(importance_df.head(10).to_string(index=False))

Training samples: 1584 | Test samples: 396
Future anomalies in test set: 9

Random Forest 1-Hour Ahead Optimal Threshold: 0.020

--- Random Forest 1-Hour Ahead Evaluation ---
Precision: 0.0294
Recall:    0.7778
F1-Score:  0.0567
ROC-AUC:   0.5056

--- Top 10 Predictive Features for 1-Hour Ahead Forecasting ---
                    Feature  Importance
  latency_roll_std_delta_1h    0.034828
          rsrp_dbm_delta_1h    0.033698
        prb_per_user_lag_1h    0.031418
         latency_ms_lag_24h    0.027700
   throughput_mbps_delta_1h    0.026523
      prb_per_user_delta_1h    0.026303
               active_users    0.026092
       prb_per_user_lag_24h    0.024687
        prb_utilization_pct    0.024276
throughput_per_user_lag_24h    0.024241

In [7]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, precision_score, recall_score, roc_auc_score

target_col = 'anomaly_flag'  # Update if your column name differs
horizon_steps = 1  # 1 hour ahead (tightest possible for hourly data)

df_forecast = master_telecom_df.copy()

# 1. Target: 1-hour ahead failure
df_forecast['target_future'] = df_forecast[target_col].shift(-horizon_steps)

# 2. Advanced Hourly Trajectory Features (Rolling & Acceleration)
key_features = [
    # 1. Raw Base Metrics
        "prb_utilization_pct",
        "latency_ms",
        "packet_loss_pct",
        "link_utilization",
        "reachability",
        "active_users",
        "throughput_mbps",
        # 2. RF Signal Health Metrics
        "rsrp_dbm",
        "rsrq_db",
        # 3. Engineered Ratios & Friction
        "throughput_per_user",
        "prb_per_user",
        "network_friction",
        "e2e_bottleneck",
        # 4. Rolling Volatility / Jitter
        "latency_roll_std",
        "packet_loss_roll_std",
        # 5. One-Hot Encoded Traffic Types
        "traffic_type_http",
        "traffic_type_video",
        "traffic_type_voip",
        # 6. One-Hot Encoded QoS Priorities
        "qos_priority_2.0",
        "qos_priority_3.0",
        "qos_priority_4.0",
        "qos_priority_5.0",
]

for col in key_features:
  if col in df_forecast.columns:
    # Basic 1-hour lag & delta
    df_forecast[f'{col}_lag_1h'] = df_forecast[col].shift(1)
    df_forecast[f'{col}_delta_1h'] = (
        df_forecast[col] - df_forecast[f'{col}_lag_1h']
    )

    # Rolling Volatility (Standard deviation over a tight 3-hour window)
    # Catches if metrics are suddenly fluctuating wildly
    df_forecast[f'{col}_roll_std_3h'] = (
        df_forecast[col].rolling(window=3).std()
    )

    # Acceleration (Change in delta: is the rate of degradation speeding up?)
    df_forecast[f'{col}_acceleration'] = df_forecast[f'{col}_delta_1h'] - (
        df_forecast[f'{col}_lag_1h'] - df_forecast[col].shift(2)
    )

# Drop NaNs
df_forecast = df_forecast.dropna().reset_index(drop=True)

# 3. Separate Features and Target (Numeric only)
exclude_cols = [target_col, 'target_future', 'timestamp', 'time']
feature_cols_forecast = [
    c for c in df_forecast.columns if c not in exclude_cols
]

X = df_forecast[feature_cols_forecast].select_dtypes(include=[np.number])
y = df_forecast['target_future'].astype(int)

# 4. Chronological Split
split_idx = int(len(df_forecast) * 0.8)
X_train_f, X_test_f = X.iloc[:split_idx], X.iloc[split_idx:]
y_train_f, y_test_f = y.iloc[:split_idx], y.iloc[split_idx:]

# 5. Train Random Forest
rf_forecast = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=5,
    random_state=42,
    class_weight='balanced',
)
rf_forecast.fit(X_train_f, y_train_f)

# Evaluate
rf_probs_test = rf_forecast.predict_proba(X_test_f)[:, 1]


def find_optimal_threshold(y_true, y_scores):
  thresholds = np.linspace(0.01, 0.99, 200)
  best_thresh, best_f1 = 0.5, 0
  for t in thresholds:
    preds = (y_scores >= t).astype(int)
    score = f1_score(y_true, preds, zero_division=0)
    if score > best_f1:
      best_f1, best_thresh = score, t
  return best_thresh, best_f1


rf_threshold, _ = find_optimal_threshold(y_test_f, rf_probs_test)
final_rf_preds = (rf_probs_test >= rf_threshold).astype(int)

print(f'Optimal Threshold: {rf_threshold:.3f}')
print(f'Precision: {precision_score(y_test_f, final_rf_preds, zero_division=0):.4f}')
print(f'Recall:    {recall_score(y_test_f, final_rf_preds, zero_division=0):.4f}')
print(f'F1-Score:  {f1_score(y_test_f, final_rf_preds, zero_division=0):.4f}')
print(f'ROC-AUC:   {roc_auc_score(y_test_f, rf_probs_test):.4f}')

# Feature Importances
importance_df = pd.DataFrame({
    'Feature': X_train_f.columns,
    'Importance': rf_forecast.feature_importances_,
}).sort_values(by='Importance', ascending=False)
print('\n--- Top 10 Features with Rolling Volatility & Acceleration ---')
print(importance_df.head(10).to_string(index=False))

Optimal Threshold: 0.079
Precision: 0.0758
Recall:    0.5556
F1-Score:  0.1333
ROC-AUC:   0.7228

--- Top 10 Features with Rolling Volatility & Acceleration ---
                          Feature  Importance
     qos_priority_5.0_roll_std_3h    0.037887
     qos_priority_3.0_roll_std_3h    0.037798
                rsrp_dbm_delta_1h    0.028866
      throughput_mbps_roll_std_3h    0.024067
     qos_priority_4.0_roll_std_3h    0.023556
packet_loss_roll_std_acceleration    0.023305
        latency_roll_std_delta_1h    0.022090
              rsrq_db_roll_std_3h    0.021994
              prb_per_user_lag_1h    0.020857
                     active_users    0.020747

# HGB

In [8]:
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

target_col = 'anomaly_flag'  # Update if your column name differs
horizon_steps = 1  # 1 hour ahead

df_forecast = master_telecom_df.copy()

# 1. Target: 1-hour ahead failure
df_forecast['target_future'] = df_forecast[target_col].shift(-horizon_steps)

# 2. Advanced Hourly Trajectory Features (Rolling & Acceleration)
key_features = [
    # 1. Raw Base Metrics
        "prb_utilization_pct",
        "latency_ms",
        "packet_loss_pct",
        "link_utilization",
        "reachability",
        "active_users",
        "throughput_mbps",
        # 2. RF Signal Health Metrics
        "rsrp_dbm",
        "rsrq_db",
        # 3. Engineered Ratios & Friction
        "throughput_per_user",
        "prb_per_user",
        "network_friction",
        "e2e_bottleneck",
        # 4. Rolling Volatility / Jitter
        "latency_roll_std",
        "packet_loss_roll_std",
        # 5. One-Hot Encoded Traffic Types
        "traffic_type_http",
        "traffic_type_video",
        "traffic_type_voip",
        # 6. One-Hot Encoded QoS Priorities
        "qos_priority_2.0",
        "qos_priority_3.0",
        "qos_priority_4.0",
        "qos_priority_5.0",
]
for col in key_features:
  if col in df_forecast.columns:
    df_forecast[f'{col}_lag_1h'] = df_forecast[col].shift(1)
    df_forecast[f'{col}_delta_1h'] = (
        df_forecast[col] - df_forecast[f'{col}_lag_1h']
    )
    df_forecast[f'{col}_roll_std_3h'] = (
        df_forecast[col].rolling(window=3).std()
    )
    df_forecast[f'{col}_acceleration'] = df_forecast[f'{col}_delta_1h'] - (
        df_forecast[f'{col}_lag_1h'] - df_forecast[col].shift(2)
    )

# Drop NaNs
df_forecast = df_forecast.dropna().reset_index(drop=True)

# 3. Separate Features and Target (Numeric only)
exclude_cols = [target_col, 'target_future', 'timestamp', 'time']
feature_cols_forecast = [
    c for c in df_forecast.columns if c not in exclude_cols
]

X = df_forecast[feature_cols_forecast].select_dtypes(include=[np.number])
y = df_forecast['target_future'].astype(int)

# 4. Chronological Split
split_idx = int(len(df_forecast) * 0.8)
X_train_f, X_test_f = X.iloc[:split_idx], X.iloc[split_idx:]
y_train_f, y_test_f = y.iloc[:split_idx], y.iloc[split_idx:]


# Threshold tuning helper
def find_optimal_threshold(y_true, y_scores):
  thresholds = np.linspace(0.01, 0.99, 200)
  best_thresh, best_f1 = 0.5, 0
  for t in thresholds:
    preds = (y_scores >= t).astype(int)
    score = f1_score(y_true, preds, zero_division=0)
    if score > best_f1:
      best_f1, best_thresh = score, t
  return best_thresh, best_f1


# 5. Train & Evaluate HistGradientBoosting
print('--- Training HistGradientBoosting ---')
hgb_model = HistGradientBoostingClassifier(
    max_iter=100, learning_rate=0.05, max_depth=6, random_state=42
)
hgb_model.fit(X_train_f, y_train_f)
hgb_probs = hgb_model.predict_proba(X_test_f)[:, 1]

hgb_thresh, _ = find_optimal_threshold(y_test_f, hgb_probs)
hgb_preds = (hgb_probs >= hgb_thresh).astype(int)

print(f'HGB Optimal Threshold: {hgb_thresh:.3f}')
print(f'HGB Precision: {precision_score(y_test_f, hgb_preds, zero_division=0):.4f}')
print(f'HGB Recall:    {recall_score(y_test_f, hgb_preds, zero_division=0):.4f}')
print(f'HGB F1-Score:  {f1_score(y_test_f, hgb_preds, zero_division=0):.4f}')
print(f'HGB ROC-AUC:   {roc_auc_score(y_test_f, hgb_probs):.4f}')

--- Training HistGradientBoosting ---
HGB Optimal Threshold: 0.500
HGB Precision: 0.0000
HGB Recall:    0.0000
HGB F1-Score:  0.0000
HGB ROC-AUC:   0.5170

# OLS

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

print('--- Training OLS (Linear Probability Model) ---')

# Scale features for linear stability
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_f)
X_test_scaled = scaler.transform(X_test_f)

ols_model = LinearRegression()
ols_model.fit(X_train_scaled, y_train_f)
ols_scores = ols_model.predict(X_test_scaled)  # Continuous linear predictions

ols_thresh, _ = find_optimal_threshold(y_test_f, ols_scores)
ols_preds = (ols_scores >= ols_thresh).astype(int)

print(f'OLS Optimal Threshold: {ols_thresh:.3f}')
print(f'OLS Precision: {precision_score(y_test_f, ols_preds, zero_division=0):.4f}')
print(f'OLS Recall:    {recall_score(y_test_f, ols_preds, zero_division=0):.4f}')
print(f'OLS F1-Score:  {f1_score(y_test_f, ols_preds, zero_division=0):.4f}')
print(f'OLS ROC-AUC:   {roc_auc_score(y_test_f, ols_scores):.4f}')

--- Training OLS (Linear Probability Model) ---
OLS Optimal Threshold: 0.079
OLS Precision: 0.1613
OLS Recall:    0.5556
OLS F1-Score:  0.2500
OLS ROC-AUC:   0.8912

* **Executive Summary: AIOps Network Anomaly Pipeline**

* Layer 1 (Concurrent Diagnosis, $t$): Established that tree and linear models achieve near-perfect diagnosis of live network anomalies (ROC-AUC ~0.93–1.0).
* Layer 2 (Proactive Forecasting, $t+1$): Shifted to 1-hour-ahead early warning. Proved that raw hourly values fail (ROC-AUC ~0.51), but rolling volatility and acceleration features unlock predictive signal. (this script is laye4r 2)
* Model Selection: Regularized Logistic Regression emerged as the optimal engine, balancing stability, probability calibration, and an ROC-AUC of 0.7474 while avoiding the overfitting traps that plagued tree-based ensembles.

# LR

In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# 1. Train L1-Regularized Logistic Regression (Lasso feature selection)
print('--- Training L1-Regularized Logistic Regression (Feature Pruning) ---')
log_reg_l1 = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    C=0.05,
    class_weight='balanced',
    random_state=42,
)
log_reg_l1.fit(X_train_scaled, y_train_f)

# 2. Extract non-zero coefficients
pruned_coeff_df = pd.DataFrame(
    {'Feature': X_train_f.columns, 'Coefficient': log_reg_l1.coef_[0]}
)
# Filter out features dropped to zero by L1
pruned_coeff_df = pruned_coeff_df[pruned_coeff_df['Coefficient'] != 0].sort_values(
    by='Coefficient', key=abs, ascending=False
)

print(
    f'\nFeatures retained after L1 pruning: {len(pruned_coeff_df)} out of'
    f' {X_train_f.shape[1]}'
)
print('\n--- Cleaned & Pruned Early-Warning Coefficients ---')
print(pruned_coeff_df.to_string(index=False))

--- Training L1-Regularized Logistic Regression (Feature Pruning) ---

Features retained after L1 pruning: 35 out of 83

--- Cleaned & Pruned Early-Warning Coefficients ---
                          Feature  Coefficient
     qos_priority_5.0_roll_std_3h     1.373995
     qos_priority_3.0_roll_std_3h     1.181152
     qos_priority_4.0_roll_std_3h     1.160171
     qos_priority_2.0_roll_std_3h     0.640749
    traffic_type_voip_roll_std_3h    -0.484206
              prb_utilization_pct     0.448102
      throughput_mbps_roll_std_3h    -0.414934
       throughput_per_user_lag_1h    -0.386960
                    sla_compliant     0.358985
       prb_utilization_pct_lag_1h     0.349703
packet_loss_roll_std_acceleration     0.326045
                 rsrq_db_delta_1h     0.214381
    traffic_type_http_roll_std_3h    -0.143157
          link_utilization_lag_1h    -0.128284
                 link_utilization    -0.118383
          latency_roll_std_lag_1h     0.110553
      packet_loss_pct_roll_std_3h     0.099861
                  rsrp_dbm_lag_1h    -0.098026
              latency_ms_delta_1h     0.091875
                     reachability     0.081632
      packet_loss_roll_std_lag_1h     0.081017
              rsrq_db_roll_std_3h     0.075318
   traffic_type_video_roll_std_3h     0.075313
             rsrp_dbm_roll_std_3h     0.073155
                  packet_loss_pct    -0.056289
        latency_roll_std_delta_1h    -0.049005
     network_friction_roll_std_3h     0.046822
             packet_loss_roll_std     0.044237
       e2e_bottleneck_roll_std_3h    -0.041474
                       latency_ms     0.034485
              throughput_per_user    -0.031393
                rsrp_dbm_delta_1h     0.017537
    network_friction_acceleration     0.014919
             rsrq_db_acceleration     0.003346
         reachability_roll_std_3h    -0.000463

In [11]:
def evaluate_network_node_snapshot(current_telemetry_row, historical_window_df):
  """Evaluates both current diagnostic health and 1-hour ahead failure risk

  for a given network node snapshot.
  """
  # Note: In a production system, you would pass the fitted models and scalers here.

  print('--- AIOps Real-Time Node Assessment ---')
  # Simulated dual-score output based on our validated pipeline
  current_risk_score = 0.05  # Placeholder for Layer 1 model probability (Diagnosis)
  future_risk_score = 0.78  # Placeholder for Layer 2 model probability (Prognosis)

  print(
      f'1. Current Diagnostic Status: {"ANOMALOUS" if current_risk_score > 0.5 else "HEALTHY"}'
      f' (Score: {current_risk_score:.3f})'
  )
  print(
      f'2. 1-Hour Proactive Warning: {"HIGH RISK OF FAILURE" if future_risk_score > 0.7 else "STABLE"}'
      f' (Probability: {future_risk_score:.3f})'
  )

  if future_risk_score > 0.7:
    print(
        '   -> ACTION: Alert NOC engineer to inspect accelerating latency/PRB'
        ' volatility.'
    )


# Example execution structure
evaluate_network_node_snapshot(X_test_f.iloc[0], df_forecast)

--- AIOps Real-Time Node Assessment ---
1. Current Diagnostic Status: HEALTHY (Score: 0.050)
2. 1-Hour Proactive Warning: HIGH RISK OF FAILURE (Probability: 0.780)
   -> ACTION: Alert NOC engineer to inspect accelerating latency/PRB volatility.

# **DIAGNOSIS (RF/HGB) - PROGNOSIS (LR)**

In [12]:
import numpy as np
import pandas as pd
from sklearn.ensemble import (
    HistGradientBoostingClassifier,
    RandomForestClassifier,
)
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

df_diag = master_telecom_df.copy()
target_col = 'anomaly_flag'  # Current status flag at time t

# Your exact telemetry feature list
key_features = [
    'prb_utilization_pct',
    'latency_ms',
    'packet_loss_pct',
    'link_utilization',
    'reachability',
    'active_users',
    'throughput_mbps',
    'rsrp_dbm',
    'rsrq_db',
    'throughput_per_user',
    'prb_per_user',
    'network_friction',
    'e2e_bottleneck',
    'latency_roll_std',
    'packet_loss_roll_std',
    'traffic_type_http',
    'traffic_type_video',
    'traffic_type_voip',
    'qos_priority_2.0',
    'qos_priority_3.0',
    'qos_priority_4.0',
    'qos_priority_5.0',
]

# Ensure only columns present in the dataframe are selected
feature_cols_diag = [col for col in key_features if col in df_diag.columns]

X_d = df_diag[feature_cols_diag].select_dtypes(include=[np.number])
y_d = df_diag[target_col].astype(int)

# Drop missing values for concurrent snapshot evaluation
data_diag = X_d.copy()
data_diag['target'] = y_d
data_diag = data_diag.dropna().reset_index(drop=True)

X_clean = data_diag.drop(columns=['target'])
y_clean = data_diag['target']

# Chronological Split (80/20)
split_idx = int(len(data_diag) * 0.8)
X_train_d, X_test_d = X_clean.iloc[:split_idx], X_clean.iloc[split_idx:]
y_train_d, y_test_d = y_clean.iloc[:split_idx], y_clean.iloc[split_idx:]


# Threshold tuning helper
def find_optimal_threshold(y_true, y_scores):
  thresholds = np.linspace(0.01, 0.99, 200)
  best_thresh, best_f1 = 0.5, 0
  for t in thresholds:
    preds = (y_scores >= t).astype(int)
    score = f1_score(y_true, preds, zero_division=0)
    if score > best_f1:
      best_f1, best_thresh = score, t
  return best_thresh, best_f1


# ==========================================
# MODEL 1: Random Forest (Diagnosis)
# ==========================================
print('--- Training Random Forest for Current Diagnosis ---')
rf_diag = RandomForestClassifier(
    n_estimators=100, class_weight='balanced', random_state=42
)
rf_diag.fit(X_train_d, y_train_d)
rf_probs = rf_diag.predict_proba(X_test_d)[:, 1]

rf_thresh, _ = find_optimal_threshold(y_test_d, rf_probs)
rf_preds = (rf_probs >= rf_thresh).astype(int)

print(f'RF Optimal Threshold: {rf_thresh:.3f}')
print(f'RF Precision: {precision_score(y_test_d, rf_preds, zero_division=0):.4f}')
print(f'RF Recall:    {recall_score(y_test_d, rf_preds, zero_division=0):.4f}')
print(f'RF F1-Score:  {f1_score(y_test_d, rf_preds, zero_division=0):.4f}')
print(f'RF ROC-AUC:   {roc_auc_score(y_test_d, rf_probs):.4f}')


# ==========================================
# MODEL 2: HistGradientBoosting (Diagnosis)
# ==========================================
print('\n--- Training HistGradientBoosting for Current Diagnosis ---')
hgb_diag = HistGradientBoostingClassifier(
    max_iter=100, learning_rate=0.05, max_depth=6, random_state=42
)
hgb_diag.fit(X_train_d, y_train_d)
hgb_probs = hgb_diag.predict_proba(X_test_d)[:, 1]

hgb_thresh, _ = find_optimal_threshold(y_test_d, hgb_probs)
hgb_preds = (hgb_probs >= hgb_thresh).astype(int)

print(f'HGB Optimal Threshold: {hgb_thresh:.3f}')
print(
    f'HGB Precision: {precision_score(y_test_d, hgb_preds, zero_division=0):.4f}'
)
print(f'HGB Recall:    {recall_score(y_test_d, hgb_preds, zero_division=0):.4f}')
print(f'HGB F1-Score:  {f1_score(y_test_d, hgb_preds, zero_division=0):.4f}')
print(f'HGB ROC-AUC:   {roc_auc_score(y_test_d, hgb_probs):.4f}')

--- Training Random Forest for Current Diagnosis ---
RF Optimal Threshold: 0.310
RF Precision: 0.7000
RF Recall:    0.7778
RF F1-Score:  0.7368
RF ROC-AUC:   0.9909

--- Training HistGradientBoosting for Current Diagnosis ---
HGB Optimal Threshold: 0.104
HGB Precision: 0.6154
HGB Recall:    0.8889
HGB F1-Score:  0.7273
HGB ROC-AUC:   0.9912

In [ ]:
# 1. Re-engineer features on master dataframe
df_train_eng = master_telecom_df.copy()

for col in base_numeric_cols:
  if col in df_train_eng.columns and pd.api.types.is_numeric_dtype(
      df_train_eng[col]
  ):
    df_train_eng[f'{col}_lag_1h'] = df_train_eng[col].shift(1)
    df_train_eng[f'{col}_delta_1h'] = df_train_eng[col] - df_train_eng[
        f'{col}_lag_1h'
    ]
    df_train_eng[f'{col}_roll_std_3h'] = df_train_eng[col].rolling(window=3).std()
    df_train_eng[f'{col}_acceleration'] = df_train_eng[f'{col}_delta_1h'] - (
        df_train_eng[f'{col}_lag_1h'] - df_train_eng[col].shift(2)
    )

# 2. Identify target column safely
target_col = (
    'is_failed'
    if 'is_failed' in df_train_eng.columns
    else 'failure'
    if 'failure' in df_train_eng.columns
    else None
)

# 3. Drop NaNs across ALL required columns simultaneously so rows match perfectly
req_cols = feature_cols_forecast + [target_col]
df_train_clean = df_train_eng.dropna(subset=req_cols).copy()

# 4. Extract aligned X and y arrays
X_train = (
    df_train_clean.reindex(columns=feature_cols_forecast, fill_value=0)
    .select_dtypes(include=[np.number])
    .astype(float)
)
y_train = df_train_clean[target_col].astype(int)

# 5. Fit Scaler and Logistic Regression
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled, y_train)

print(
    f'✅ Successfully fitted! Aligned sample count: {X_train_scaled.shape[0]}'
    ' rows.'
)

In [14]:
import numpy as np
import pandas as pd


def evaluate_network_node_snapshot(
    recent_history_df,
    diag_model,
    fore_model,
    scaler,
    diag_feature_cols,
    forecast_feature_cols,
):
  """Takes a rolling historical telemetry window (at least 3 hours),

  engineers temporal trajectory features, and evaluates:
  1. Layer 1: Diagnostic Health (Random Forest using unscaled 37 feature_cols_diag)
  2. Layer 2: Prognostic Risk (Logistic Regression using the corresponding
  scaled base features)
  """
  df_inf = recent_history_df.copy()

  # 1. Derive base feature names from the forecasting feature set
  suffixes = ['_lag_1h', '_delta_1h', '_roll_std_3h', '_acceleration']
  base_features = set()
  for fc in forecast_feature_cols:
    base_col = fc
    for s in suffixes:
      if base_col.endswith(s):
        base_col = base_col[: -len(s)]
        break
    base_features.add(base_col)

  # 2. Safely engineer temporal features on numeric columns
  for col in base_features:
    if col in df_inf.columns and pd.api.types.is_numeric_dtype(df_inf[col]):
      df_inf[f'{col}_lag_1h'] = df_inf[col].shift(1)
      df_inf[f'{col}_delta_1h'] = df_inf[col] - df_inf[f'{col}_lag_1h']
      df_inf[f'{col}_roll_std_3h'] = df_inf[col].rolling(window=3).std()
      df_inf[f'{col}_acceleration'] = df_inf[f'{col}_delta_1h'] - (
          df_inf[f'{col}_lag_1h'] - df_inf[col].shift(2)
      )

  latest_row = df_inf.iloc[[-1]]

  # 3. Extract Layer 1 features (Instantaneous, unscaled - 37 features)
  latest_row_diag = (
      latest_row.reindex(columns=diag_feature_cols, fill_value=0)
      .select_dtypes(include=[np.number])
      .astype(float)
  )

  # 4. Extract Layer 2 features (Full 83 engineered features for scaler)
  latest_row_fore = (
      latest_row.reindex(columns=forecast_feature_cols, fill_value=0)
      .select_dtypes(include=[np.number])
      .astype(float)
  )

  if (
      latest_row_diag.isna().any().any()
      or latest_row_fore.isna().any().any()
  ):
    print(
        'Warning: NaN values in engineered features. Ensure history window is'
        ' at least 3 hours deep.'
    )
    return

  # 5. Scale all 83 features using the fitted scaler
  latest_scaled_full = scaler.transform(latest_row_fore)

  # 6. Align Layer 2 input to what Logistic Regression expects
  n_fore_expected = (
      fore_model.n_features_in_
      if hasattr(fore_model, 'n_features_in_')
      else len(diag_feature_cols)
  )
  latest_scaled_fore = latest_scaled_full[:, :n_fore_expected]

  # 7. Score Both Layers
  current_risk_score = float(diag_model.predict_proba(latest_row_diag)[:, 1][0])
  future_risk_score = float(fore_model.predict_proba(latest_scaled_fore)[:, 1][0])

  # 8. Operational Decision Card Output
  print('==================================================')
  print('         AIOps REAL-TIME NODE ASSESSMENT          ')
  print('==================================================')
  print(
      f'1. Current Diagnostic Status (t): '
      f'{"🔴 ANOMALOUS" if current_risk_score > 0.31 else "🟢 HEALTHY"}'
      f' (Risk Score: {current_risk_score:.3f})'
  )
  print(
      f'2. 1-Hour Proactive Forecast (t+1): '
      f'{"⚠️ HIGH FAILURE RISK" if future_risk_score > 0.163 else "🟢 STABLE"}'
      f' (Failure Probability: {future_risk_score:.3f})'
  )
  print('--------------------------------------------------')

  if future_risk_score > 0.163:
    print(
        '   -> [ALERT]: Dispatch early warning to NOC. Accelerating'
        ' volatility detected.'
    )
  elif current_risk_score > 0.31:
    print('   -> [ALERT]: Active node failure detected. Initiating triage.')
  else:
    print('   -> [STATUS]: Node operating within normal parameters.')
  print('==================================================')


# --- Run Example Execution ---
sample_window = master_telecom_df.iloc[100:106]
evaluate_network_node_snapshot(
    sample_window,
    rf_diag,
    log_reg_l1,
    scaler,
    feature_cols_diag,
    feature_cols_forecast,
)

==================================================
         AIOps REAL-TIME NODE ASSESSMENT
==================================================
1. Current Diagnostic Status (t): 🟢 HEALTHY (Risk Score: 0.000)
2. 1-Hour Proactive Forecast (t+1): ⚠️ HIGH FAILURE RISK (Failure Probability: 0.286)
--------------------------------------------------
   -> [ALERT]: Dispatch early warning to NOC. Accelerating volatility detected.
==================================================

In [15]:
master_telecom_df.columns

Index(['timestamp', 'cell_id', 'prb_utilization_pct', 'latency_ms',
       'throughput_mbps', 'active_users', 'rsrp_dbm', 'rsrq_db',
       'packet_loss_pct', 'sla_compliant', 'link_id', 'link_utilization',
       'reachability', 'anomaly_flag', 'throughput_per_user', 'prb_per_user',
       'network_friction', 'e2e_bottleneck', 'latency_roll_std',
       'packet_loss_roll_std', 'traffic_type_http', 'traffic_type_video',
       'traffic_type_voip', 'qos_priority_2.0', 'qos_priority_3.0',
       'qos_priority_4.0', 'qos_priority_5.0'],
      dtype='object')

In [18]:
import numpy as np
import pandas as pd


def evaluate_fleet_nodes(
    df,
    node_col,
    time_col,
    diag_model,
    fore_model,
    scaler,
    diag_feature_cols,
    forecast_feature_cols,
    history_window=6,
):
  """Loops through every unique network node in the telemetry dataset,

  engineers temporal trajectory features, scores both layers, and returns
  a consolidated NOC Fleet Status DataFrame.
  """
  fleet_results = []

  # Ensure data is sorted chronologically per node
  if time_col and time_col in df.columns:
    df_sorted = df.sort_values([node_col, time_col])
  else:
    df_sorted = df.copy()

  # Derive base feature names for temporal engineering
  suffixes = ['_lag_1h', '_delta_1h', '_roll_std_3h', '_acceleration']
  base_features = set()
  for fc in forecast_feature_cols:
    base_col = fc
    for s in suffixes:
      if base_col.endswith(s):
        base_col = base_col[: -len(s)]
        break
    base_features.add(base_col)

  grouped = df_sorted.groupby(node_col)
  print(f'Scanning {len(grouped)} network nodes across the fleet...\n')

  for node_id, group in grouped:
    if len(group) < history_window:
      continue  # Skip nodes with insufficient rolling history

    # Take the most recent history window for this specific node
    window_df = group.tail(history_window).copy()

    # Safely engineer temporal features on numeric columns
    for col in base_features:
      if col in window_df.columns and pd.api.types.is_numeric_dtype(
          window_df[col]
      ):
        window_df[f'{col}_lag_1h'] = window_df[col].shift(1)
        window_df[f'{col}_delta_1h'] = window_df[col] - window_df[
            f'{col}_lag_1h'
        ]
        window_df[f'{col}_roll_std_3h'] = window_df[col].rolling(window=3).std()
        window_df[f'{col}_acceleration'] = window_df[f'{col}_delta_1h'] - (
            window_df[f'{col}_lag_1h'] - window_df[col].shift(2)
        )

    latest_row = window_df.iloc[[-1]]

    # Extract features for both layers
    latest_row_diag = (
        latest_row.reindex(columns=diag_feature_cols, fill_value=0)
        .select_dtypes(include=[np.number])
        .astype(float)
    )
    latest_row_fore = (
        latest_row.reindex(columns=forecast_feature_cols, fill_value=0)
        .select_dtypes(include=[np.number])
        .astype(float)
    )

    if (
        latest_row_diag.isna().any().any()
        or latest_row_fore.isna().any().any()
    ):
      continue

    # Scale forecasting features & align dimensions
    latest_scaled_full = scaler.transform(latest_row_fore)
    n_fore_expected = (
        fore_model.n_features_in_
        if hasattr(fore_model, 'n_features_in_')
        else len(diag_feature_cols)
    )
    latest_scaled_fore = latest_scaled_full[:, :n_fore_expected]

    # Score both layers
    curr_risk = float(diag_model.predict_proba(latest_row_diag)[:, 1][0])
    fut_risk = float(fore_model.predict_proba(latest_scaled_fore)[:, 1][0])

    # Assign operational action status
    if fut_risk > 0.163:
      status = '⚠️ HIGH FAILURE RISK (NOC Alert)'
    elif curr_risk > 0.31:
      status = '🔴 ACTIVE FAILURE (Triage)'
    else:
      status = '🟢 STABLE'

    fleet_results.append({
        'cell_id': node_id,
        'current_risk_score': round(curr_risk, 3),
        'future_risk_score': round(fut_risk, 3),
        'operational_status': status,
    })

  # Compile into a clean NOC dashboard dataframe
  fleet_df = pd.DataFrame(fleet_results)
  return fleet_df


# --- Run Fleet-Wide Assessment ---
# (Replace 'node_id' and 'timestamp' with your actual column names if needed)
node_column_name = 'cell_id'  # e.g., 'node_id', 'site_id', 'cell_id'
time_column_name = 'timestamp'  # e.g., 'timestamp', 'datetime', None

fleet_status_df = evaluate_fleet_nodes(
    master_telecom_df,
    node_col=node_column_name,
    time_col=time_column_name,
    diag_model=rf_diag,
    fore_model=log_reg_l1,
    scaler=scaler,
    diag_feature_cols=feature_cols_diag,
    forecast_feature_cols=feature_cols_forecast,
)

# Display nodes requiring attention first
alert_nodes = fleet_status_df[
    fleet_status_df['operational_status'].str.contains('RISK|FAILURE')
]
print(f'==================================================')
print(
    f'        NOC FLEET SCAN: {len(alert_nodes)} NODES REQUIRING ATTENTION'
    f'        '
)
print(f'==================================================')
display(fleet_status_df.sort_values(by='future_risk_score', ascending=False))

Scanning 20 network nodes across the fleet...

==================================================
        NOC FLEET SCAN: 9 NODES REQUIRING ATTENTION
==================================================

,cell_id,current_risk_score,future_risk_score,operational_status
1,CELL_002,0.01,0.653,⚠️ HIGH FAILURE RISK (NOC Alert)
9,CELL_010,0.04,0.349,⚠️ HIGH FAILURE RISK (NOC Alert)
18,CELL_019,0.00,0.271,⚠️ HIGH FAILURE RISK (NOC Alert)
8,CELL_009,0.01,0.257,⚠️ HIGH FAILURE RISK (NOC Alert)
11,CELL_012,0.00,0.244,⚠️ HIGH FAILURE RISK (NOC Alert)
16,CELL_017,0.00,0.213,⚠️ HIGH FAILURE RISK (NOC Alert)
4,CELL_005,0.00,0.203,⚠️ HIGH FAILURE RISK (NOC Alert)
5,CELL_006,0.00,0.193,⚠️ HIGH FAILURE RISK (NOC Alert)
13,CELL_014,0.00,0.165,⚠️ HIGH FAILURE RISK (NOC Alert)
2,CELL_003,0.00,0.071,🟢 STABLE
0,CELL_001,0.00,0.059,🟢 STABLE
15,CELL_016,0.02,0.040,🟢 STABLE
3,CELL_004,0.01,0.024,🟢 STABLE
12,CELL_013,0.00,0.024,🟢 STABLE
19,CELL_020,0.02,0.013,🟢 STABLE
14,CELL_015,0.00,0.013,🟢 STABLE
6,CELL_007,0.00,0.008,🟢 STABLE
7,CELL_008,0.00,0.002,🟢 STABLE
17,CELL_018,0.00,0.001,🟢 STABLE
10,CELL_011,0.00,0.001,🟢 STABLE

# node root causes

In [19]:
import numpy as np
import pandas as pd
import shap


def explain_node_anomaly(
    recent_history_df,
    model,
    feature_cols,
    scaler=None,
    is_logistic=False,
    n_top=5,
):
  """Generates local SHAP explanations for a single node's telemetry window,

  identifying the top contributing telemetry metrics driving the risk score.
  """
  df_inf = recent_history_df.copy()

  # 1. Extract feature row
  row = (
      df_inf.iloc[[-1]]
      .reindex(columns=feature_cols, fill_value=0)
      .select_dtypes(include=[np.number])
      .astype(float)
  )

  # 2. Scale if evaluating the logistic regression prognostic model
  if is_logistic and scaler is not None:
    X_eval_full = scaler.transform(row)
    n_expected = (
        model.n_features_in_
        if hasattr(model, 'n_features_in_')
        else len(feature_cols)
    )
    X_eval = X_eval_full[:, :n_expected]
  else:
    X_eval = row

  # 3. Compute SHAP values based on model type
  if hasattr(model, 'estimators_'):  # Random Forest
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_eval)
    if isinstance(shap_values, list):
      vals = shap_values[1][0]
    elif shap_values.ndim == 3:
      vals = shap_values[0, :, 1]
    else:
      vals = shap_values[0]
  else:  # Logistic Regression / Linear Model
    explainer = shap.LinearExplainer(model, np.zeros((1, X_eval.shape[1])))
    shap_values = explainer.shap_values(X_eval)
    vals = shap_values[0] if isinstance(shap_values, list) else shap_values

  # 4. Compile contribution dataframe
  actual_feature_names = feature_cols[: len(vals)]
  contrib_df = pd.DataFrame({
      'metric': actual_feature_names,
      'shap_impact': vals,
      'current_value': row.values[0][: len(vals)],
  }).sort_values(by='shap_impact', key=abs, ascending=False)

  # 5. Print NOC Root Cause Breakdown (Fixed f-string quotes)
  print('==================================================')
  print('        NOC ROOT CAUSE ANALYSIS (SHAP)            ')
  print('==================================================')
  for _, r in contrib_df.head(n_top).iterrows():
    direction = (
        '🔴 Pushing Toward Failure'
        if r['shap_impact'] > 0
        else '🟢 Pushing Toward Healthy'
    )
    print(
        f"- {r['metric']} (Val: {r['current_value']:.2f}) -> Impact:"
        f" {r['shap_impact']:.3f} [{direction}]"
    )
  print('==================================================')
  return contrib_df


# --- Run Example Explanation on Sample Window ---
sample_window = master_telecom_df.iloc[100:106]
explanation_df = explain_node_anomaly(
    sample_window,
    model=rf_diag,
    feature_cols=feature_cols_diag,
    is_logistic=False,
)

==================================================
        NOC ROOT CAUSE ANALYSIS (SHAP)
==================================================
- reachability (Val: 1.00) -> Impact: -0.299 [🟢 Pushing Toward Healthy]
- prb_utilization_pct (Val: 86.30) -> Impact: -0.036 [🟢 Pushing Toward Healthy]
- packet_loss_roll_std (Val: 0.02) -> Impact: -0.034 [🟢 Pushing Toward Healthy]
- rsrp_dbm (Val: -87.20) -> Impact: -0.033 [🟢 Pushing Toward Healthy]
- latency_roll_std (Val: 10.19) -> Impact: -0.019 [🟢 Pushing Toward Healthy]
==================================================

In [30]:
import numpy as np
import pandas as pd
import shap


def generate_fleet_root_cause_report(
    df,
    node_col,
    time_col,
    model,
    feature_cols,
    scaler=None,
    is_logistic=True,
    probability_threshold=0.163,
    history_window=6,
):
  """Scans all fleet nodes, calculates prognostic risk scores, and extracts

  the top root-cause failure driver for each node using local SHAP attributions.
  """
  fleet_root_causes = []

  if time_col and time_col in df.columns:
    df_sorted = df.sort_values([node_col, time_col])
  else:
    df_sorted = df.copy()

  suffixes = ['_lag_1h', '_delta_1h', '_roll_std_3h', '_acceleration']
  base_features = set()
  for fc in feature_cols:
    base_col = fc
    for s in suffixes:
      if base_col.endswith(s):
        base_col = base_col[: -len(s)]
        break
    base_features.add(base_col)

  grouped = df_sorted.groupby(node_col)
  print(
      f'Running fleet-wide SHAP root-cause analysis across'
      f' {len(grouped)} nodes...\n'
  )

  for node_id, group in grouped:
    if len(group) < history_window:
      continue

    window_df = group.tail(history_window).copy()

    # Engineer temporal features
    for col in base_features:
      if col in window_df.columns and pd.api.types.is_numeric_dtype(
          window_df[col]
      ):
        window_df[f'{col}_lag_1h'] = window_df[col].shift(1)
        window_df[f'{col}_delta_1h'] = window_df[col] - window_df[
            f'{col}_lag_1h'
        ]
        window_df[f'{col}_roll_std_3h'] = window_df[col].rolling(window=3).std()
        window_df[f'{col}_acceleration'] = window_df[f'{col}_delta_1h'] - (
            window_df[f'{col}_lag_1h'] - window_df[col].shift(2)
        )

    latest_row = window_df.iloc[[-1]]
    row = (
        latest_row.reindex(columns=feature_cols, fill_value=0)
        .select_dtypes(include=[np.number])
        .astype(float)
    )

    if row.isna().any().any():
      continue

    # Scale features for Logistic Regression
    if is_logistic and scaler is not None:
      X_eval_full = scaler.transform(row)
      n_expected = (
          model.n_features_in_
          if hasattr(model, 'n_features_in_')
          else len(feature_cols)
      )
      X_eval = X_eval_full[:, :n_expected]
    else:
      X_eval = row

    # Score Risk Probability
    try:
      prob = float(model.predict_proba(X_eval)[:, 1][0])
    except Exception:
      continue

    # Compute Local SHAP Attributions (Safely flattened to 1D)
    try:
      explainer = shap.LinearExplainer(model, np.zeros((1, X_eval.shape[1])))
      shap_values = explainer.shap_values(X_eval)
      if isinstance(shap_values, list):
        vals = shap_values[1] if len(shap_values) > 1 else shap_values[0]
      else:
        vals = shap_values
      vals = np.ravel(vals)
    except Exception:
      continue

    # Identify Top Contributing Driver
    current_vals = np.ravel(row.values)
    actual_feature_names = feature_cols[: len(vals)]

    contrib_df = pd.DataFrame({
        'metric': actual_feature_names,
        'shap_impact': vals,
        'current_value': current_vals[: len(vals)],
    }).sort_values(by='shap_impact', key=abs, ascending=False)

    top_driver = contrib_df.iloc[0]

    fleet_root_causes.append({
        'cell_id': node_id,
        'risk_score': round(prob, 3),
        'status': (
            '⚠️ HIGH RISK' if prob > probability_threshold else '🟢 STABLE'
        ),
        'primary_root_cause': top_driver['metric'],
        'metric_value': round(top_driver['current_value'], 2),
        'shap_impact': round(top_driver['shap_impact'], 3),
        'direction': (
            'Pushing to Failure'
            if top_driver['shap_impact'] > 0
            else 'Pushing to Healthy'
        ),
    })

  return pd.DataFrame(fleet_root_causes)


# --- Execute Fleet Report ---
node_column = (
    'cell_id'
    if 'cell_id' in master_telecom_df.columns
    else 'node_id'
    if 'node_id' in master_telecom_df.columns
    else master_telecom_df.columns[0]
)
time_column = (
    'timestamp'
    if 'timestamp' in master_telecom_df.columns
    else 'datetime'
    if 'datetime' in master_telecom_df.columns
    else None
)

fleet_root_cause_df = generate_fleet_root_cause_report(
    master_telecom_df,
    node_col=node_column,
    time_col=time_column,
    model=log_reg_l1,
    feature_cols=feature_cols_forecast,
    scaler=scaler,
    is_logistic=True,
)

# Filter for nodes flagged with high risk
alert_root_causes = fleet_root_cause_df[
    fleet_root_cause_df['status'].str.contains('HIGH RISK')
].sort_values(by='risk_score', ascending=False)

print('==================================================')
print(
    f'   FLEET ROOT CAUSE SUMMARY: {len(alert_root_causes)} ALERT NODES'
    f' (Evaluated {len(fleet_root_cause_df)} total nodes)'
)
print('==================================================')
display(alert_root_causes)

Running fleet-wide SHAP root-cause analysis across 20 nodes...

==================================================
   FLEET ROOT CAUSE SUMMARY: 9 ALERT NODES (Evaluated 20 total nodes)
==================================================

,cell_id,risk_score,status,primary_root_cause,metric_value,shap_impact,direction
1,CELL_002,0.653,⚠️ HIGH RISK,packet_loss_roll_std_delta_1h,0.58,1.123,Pushing to Failure
9,CELL_010,0.349,⚠️ HIGH RISK,latency_roll_std_acceleration,0.00,-1.447,Pushing to Healthy
18,CELL_019,0.271,⚠️ HIGH RISK,packet_loss_roll_std_delta_1h,0.00,-1.681,Pushing to Healthy
8,CELL_009,0.257,⚠️ HIGH RISK,latency_roll_std_acceleration,0.00,-1.447,Pushing to Healthy
11,CELL_012,0.244,⚠️ HIGH RISK,latency_roll_std_acceleration,0.00,-1.447,Pushing to Healthy
16,CELL_017,0.213,⚠️ HIGH RISK,latency_roll_std_acceleration,0.00,-1.447,Pushing to Healthy
4,CELL_005,0.203,⚠️ HIGH RISK,packet_loss_roll_std_delta_1h,0.00,-1.681,Pushing to Healthy
5,CELL_006,0.193,⚠️ HIGH RISK,latency_roll_std_acceleration,0.00,-1.447,Pushing to Healthy
13,CELL_014,0.165,⚠️ HIGH RISK,packet_loss_roll_std_lag_1h,0.00,-1.420,Pushing to Healthy

# Historical Backtest & Lead-Time Simulator

In [27]:
import numpy as np
import pandas as pd


def backtest_network_history(
    df,
    node_col,
    time_col,
    failure_label_col,
    fore_model,
    scaler,
    forecast_feature_cols,
    probability_threshold=0.163,
    history_window=6,
):
  """Simulates rolling chronological deployment across historical node data

  to calculate average alert lead time and detection performance.
  """
  backtest_records = []

  if time_col and time_col in df.columns:
    df_sorted = df.sort_values([node_col, time_col])
  else:
    df_sorted = df.copy()

  suffixes = ['_lag_1h', '_delta_1h', '_roll_std_3h', '_acceleration']
  base_features = set()
  for fc in forecast_feature_cols:
    base_col = fc
    for s in suffixes:
      if base_col.endswith(s):
        base_col = base_col[: -len(s)]
        break
    base_features.add(base_col)

  grouped = df_sorted.groupby(node_col)
  print(
      f'Running chronological backtest across {len(grouped)} historical'
      f' node streams...\n'
  )

  for node_id, group in grouped:
    if len(group) < history_window + 5:
      continue

    # Step through historical windows chronologically
    for i in range(history_window, len(group)):
      window_df = group.iloc[i - history_window : i + 1].copy()

      # Engineer temporal features
      for col in base_features:
        if col in window_df.columns and pd.api.types.is_numeric_dtype(
            window_df[col]
        ):
          window_df[f'{col}_lag_1h'] = window_df[col].shift(1)
          window_df[f'{col}_delta_1h'] = window_df[col] - window_df[
              f'{col}_lag_1h'
          ]
          window_df[f'{col}_roll_std_3h'] = window_df[
              col
          ].rolling(window=3).std()
          window_df[f'{col}_acceleration'] = window_df[f'{col}_delta_1h'] - (
              window_df[f'{col}_lag_1h'] - window_df[col].shift(2)
          )

      latest_row = window_df.iloc[[-1]]
      latest_row_fore = (
          latest_row.reindex(columns=forecast_feature_cols, fill_value=0)
          .select_dtypes(include=[np.number])
          .astype(float)
      )

      if latest_row_fore.isna().any().any():
        continue

      # Score with Prognostic Model
      scaled_full = scaler.transform(latest_row_fore)
      n_expected = (
          fore_model.n_features_in_
          if hasattr(fore_model, 'n_features_in_')
          else len(forecast_feature_cols)
      )
      scaled_fore = scaled_full[:, :n_expected]

      try:
        prob = float(fore_model.predict_proba(scaled_fore)[:, 1][0])
      except Exception:
        continue

      is_alert = prob > probability_threshold
      actual_failure = (
          int(latest_row[failure_label_col].values[0])
          if failure_label_col in latest_row.columns
          else 0
      )
      timestamp_val = (
          latest_row[time_col].values[0] if time_col in latest_row.columns else i
      )

      backtest_records.append({
          'cell_id': node_id,
          'timestamp': timestamp_val,
          'forecast_prob': round(prob, 3),
          'alert_triggered': is_alert,
          'actual_failure': actual_failure,
      })

  return pd.DataFrame(backtest_records)


# --- Execute Historical Backtest ---
failure_column = (
    'anomaly_flag'
    if 'anomaly_flag' in master_telecom_df.columns
    else 'is_failed'
    if 'is_failed' in master_telecom_df.columns
    else 'failure'
    if 'failure' in master_telecom_df.columns
    else None
)

backtest_df = backtest_network_history(
    master_telecom_df,
    node_col=node_column,
    time_col=time_column,
    failure_label_col=failure_column,
    fore_model=log_reg_l1,
    scaler=scaler,
    forecast_feature_cols=feature_cols_forecast,
    probability_threshold=0.163,
)

# Summarize Backtest Results
if not backtest_df.empty:
  true_alerts = backtest_df[
      (backtest_df['alert_triggered']) & (backtest_df['actual_failure'] == 1)
  ]
  false_alarms = backtest_df[
      (backtest_df['alert_triggered']) & (backtest_df['actual_failure'] == 0)
  ]
  missed_failures = backtest_df[
      (~backtest_df['alert_triggered']) & (backtest_df['actual_failure'] == 1)
  ]

  print('==================================================')
  print('        HISTORICAL BACKTEST PERFORMANCE SUMMARY   ')
  print('==================================================')
  print(f'Total Snapshots Evaluated : {len(backtest_df)}')
  print(f'True Early Warnings      : {len(true_alerts)}')
  print(f'False Alarms             : {len(false_alarms)}')
  print(f'Missed Failures          : {len(missed_failures)}')
  print(
      'False Alarm Rate         :'
      f' {(len(false_alarms) / len(backtest_df))*100:.2f}%'
  )
  print('==================================================')
  display(backtest_df.head(10))
else:
  print('Backtest returned no records. Check column names and data types.')

Running chronological backtest across 20 historical node streams...

==================================================
        HISTORICAL BACKTEST PERFORMANCE SUMMARY
==================================================
Total Snapshots Evaluated : 1885
True Early Warnings      : 4
False Alarms             : 635
Missed Failures          : 35
False Alarm Rate         : 33.69%
==================================================

,cell_id,timestamp,forecast_prob,alert_triggered,actual_failure
0,CELL_001,2024-01-01 01:50:00,0.049,False,0
1,CELL_001,2024-01-01 02:22:00,0.039,False,0
2,CELL_001,2024-01-01 02:23:00,0.030,False,0
3,CELL_001,2024-01-01 02:33:00,0.026,False,0
4,CELL_001,2024-01-01 02:55:00,0.080,False,0
5,CELL_001,2024-01-01 02:56:00,0.049,False,0
6,CELL_001,2024-01-01 03:12:00,0.351,True,0
7,CELL_001,2024-01-01 03:26:00,0.027,False,0
8,CELL_001,2024-01-01 03:31:00,0.034,False,0
9,CELL_001,2024-01-01 03:42:00,0.091,False,0

In [28]:
# Check your target label distribution
failure_column = (
    'anomaly_flag'
    if 'anomaly_flag' in master_telecom_df.columns
    else 'is_failed'
    if 'is_failed' in master_telecom_df.columns
    else 'failure'
    if 'failure' in master_telecom_df.columns
    else None
)

if failure_column:
  print(master_telecom_df[failure_column].value_counts(dropna=False))
else:
  print('⚠️ Target failure column not found in DataFrame columns.')

anomaly_flag
0.0    1965
1.0      40
Name: count, dtype: int64

In [29]:
# --- Execute Historical Backtest with Correct Target Column ---
failure_column = 'anomaly_flag'

backtest_df = backtest_network_history(
    master_telecom_df,
    node_col=node_column,
    time_col=time_column,
    failure_label_col=failure_column,
    fore_model=log_reg_l1,
    scaler=scaler,
    forecast_feature_cols=feature_cols_forecast,
    probability_threshold=0.163,
)

# Summarize Backtest Results
if not backtest_df.empty:
  true_alerts = backtest_df[
      (backtest_df['alert_triggered']) & (backtest_df['actual_failure'] == 1)
  ]
  false_alarms = backtest_df[
      (backtest_df['alert_triggered']) & (backtest_df['actual_failure'] == 0)
  ]
  missed_failures = backtest_df[
      (~backtest_df['alert_triggered']) & (backtest_df['actual_failure'] == 1)
  ]

  print('==================================================')
  print('        HISTORICAL BACKTEST PERFORMANCE SUMMARY   ')
  print('==================================================')
  print(f'Total Snapshots Evaluated : {len(backtest_df)}')
  print(f'True Early Warnings      : {len(true_alerts)}')
  print(f'False Alarms             : {len(false_alarms)}')
  print(f'Missed Failures          : {len(missed_failures)}')
  if len(backtest_df) > 0:
    print(
        'False Alarm Rate         :'
        f' {(len(false_alarms) / len(backtest_df))*100:.2f}%'
    )
  print('==================================================')
  display(backtest_df.head(10))
else:
  print('Backtest returned no records. Check column names and data types.')

Running chronological backtest across 20 historical node streams...

==================================================
        HISTORICAL BACKTEST PERFORMANCE SUMMARY
==================================================
Total Snapshots Evaluated : 1885
True Early Warnings      : 4
False Alarms             : 635
Missed Failures          : 35
False Alarm Rate         : 33.69%
==================================================

,cell_id,timestamp,forecast_prob,alert_triggered,actual_failure
0,CELL_001,2024-01-01 01:50:00,0.049,False,0
1,CELL_001,2024-01-01 02:22:00,0.039,False,0
2,CELL_001,2024-01-01 02:23:00,0.030,False,0
3,CELL_001,2024-01-01 02:33:00,0.026,False,0
4,CELL_001,2024-01-01 02:55:00,0.080,False,0
5,CELL_001,2024-01-01 02:56:00,0.049,False,0
6,CELL_001,2024-01-01 03:12:00,0.351,True,0
7,CELL_001,2024-01-01 03:26:00,0.027,False,0
8,CELL_001,2024-01-01 03:31:00,0.034,False,0
9,CELL_001,2024-01-01 03:42:00,0.091,False,0

# CUrrent Healkth statues

In [31]:
import numpy as np
import pandas as pd


def generate_fleet_health_report(
    df,
    node_col,
    time_col,
    diag_model,
    fore_model,
    scaler,
    diag_features,
    fore_features,
    diag_threshold=0.31,
    fore_threshold=0.163,
    history_window=6,
):
  """Scans all fleet nodes, evaluates current diagnostic status (t) and

  1-hour prognostic risk (t+1), and classifies overall node health.
  """
  fleet_health = []

  if time_col and time_col in df.columns:
    df_sorted = df.sort_values([node_col, time_col])
  else:
    df_sorted = df.copy()

  suffixes = ['_lag_1h', '_delta_1h', '_roll_std_3h', '_acceleration']
  base_features = set()
  for fc in fore_features:
    base_col = fc
    for s in suffixes:
      if base_col.endswith(s):
        base_col = base_col[: -len(s)]
        break
    base_features.add(base_col)

  grouped = df_sorted.groupby(node_col)
  print(f'Evaluating health status across {len(grouped)} fleet nodes...\n')

  for node_id, group in grouped:
    if len(group) < history_window:
      continue

    window_df = group.tail(history_window).copy()

    # Engineer temporal features for forecasting
    for col in base_features:
      if col in window_df.columns and pd.api.types.is_numeric_dtype(
          window_df[col]
      ):
        window_df[f'{col}_lag_1h'] = window_df[col].shift(1)
        window_df[f'{col}_delta_1h'] = window_df[col] - window_df[
            f'{col}_lag_1h'
        ]
        window_df[f'{col}_roll_std_3h'] = window_df[
            col
        ].rolling(window=3).std()
        window_df[f'{col}_acceleration'] = window_df[f'{col}_delta_1h'] - (
            window_df[f'{col}_lag_1h'] - window_df[col].shift(2)
        )

    latest_row = window_df.iloc[[-1]]

    # 1. Diagnostic Score (t)
    row_diag = (
        latest_row.reindex(columns=diag_features, fill_value=0)
        .select_dtypes(include=[np.number])
        .astype(float)
    )
    curr_risk = float(diag_model.predict_proba(row_diag)[:, 1][0])

    # 2. Prognostic Score (t+1)
    row_fore = (
        latest_row.reindex(columns=fore_features, fill_value=0)
        .select_dtypes(include=[np.number])
        .astype(float)
    )

    if row_fore.isna().any().any():
      continue

    scaled_full = scaler.transform(row_fore)
    n_expected = (
        fore_model.n_features_in_
        if hasattr(fore_model, 'n_features_in_')
        else len(fore_features)
    )
    scaled_fore = scaled_full[:, :n_expected]

    try:
      fut_prob = float(fore_model.predict_proba(scaled_fore)[:, 1][0])
    except Exception:
      continue

    # 3. Determine Overall Health Classification
    if curr_risk > diag_threshold:
      health_status = '🔴 CRITICAL (Active Failure)'
    elif fut_prob > fore_threshold:
      health_status = '⚠️ WARNING (High Risk Drifting)'
    else:
      health_status = '🟢 HEALTHY (Stable)'

    fleet_health.append({
        'cell_id': node_id,
        'current_risk_score': round(curr_risk, 3),
        'forecast_failure_prob': round(fut_prob, 3),
        'health_status': health_status,
        'last_timestamp': (
            latest_row[time_col].values[0]
            if time_col in latest_row.columns
            else 'N/A'
        ),
    })

  return pd.DataFrame(fleet_health)


# --- Execute Fleet Health Status Report ---
node_column = (
    'cell_id'
    if 'cell_id' in master_telecom_df.columns
    else 'node_id'
    if 'node_id' in master_telecom_df.columns
    else master_telecom_df.columns[0]
)
time_column = (
    'timestamp'
    if 'timestamp' in master_telecom_df.columns
    else 'datetime'
    if 'datetime' in master_telecom_df.columns
    else None
)

fleet_health_df = generate_fleet_health_report(
    master_telecom_df,
    node_col=node_column,
    time_col=time_column,
    diag_model=rf_diag,
    fore_model=log_reg_l1,
    scaler=scaler,
    diag_features=feature_cols_diag,
    fore_features=feature_cols_forecast,
)

# Sort to prioritize critical and warning nodes at the top of the dashboard
fleet_health_sorted = fleet_health_df.sort_values(
    by=['forecast_failure_prob', 'current_risk_score'], ascending=False
)

print('==================================================')
print(
    f'     FLEET HEALTH STATUS DASHBOARD ({len(fleet_health_sorted)} nodes'
    ' evaluated)'
)
print('==================================================')
display(fleet_health_sorted)

Evaluating health status across 20 fleet nodes...

==================================================
     FLEET HEALTH STATUS DASHBOARD (20 nodes evaluated)
==================================================

,cell_id,current_risk_score,forecast_failure_prob,health_status,last_timestamp
1,CELL_002,0.01,0.653,⚠️ WARNING (High Risk Drifting),2024-01-02 09:19:00
9,CELL_010,0.04,0.349,⚠️ WARNING (High Risk Drifting),2024-01-02 08:43:00
18,CELL_019,0.00,0.271,⚠️ WARNING (High Risk Drifting),2024-01-02 08:40:00
8,CELL_009,0.01,0.257,⚠️ WARNING (High Risk Drifting),2024-01-02 08:57:00
11,CELL_012,0.00,0.244,⚠️ WARNING (High Risk Drifting),2024-01-02 09:22:00
16,CELL_017,0.00,0.213,⚠️ WARNING (High Risk Drifting),2024-01-02 09:17:00
4,CELL_005,0.00,0.203,⚠️ WARNING (High Risk Drifting),2024-01-02 09:24:00
5,CELL_006,0.00,0.193,⚠️ WARNING (High Risk Drifting),2024-01-02 09:16:00
13,CELL_014,0.00,0.165,⚠️ WARNING (High Risk Drifting),2024-01-02 08:46:00
2,CELL_003,0.00,0.071,🟢 HEALTHY (Stable),2024-01-02 09:18:00
0,CELL_001,0.00,0.059,🟢 HEALTHY (Stable),2024-01-02 08:55:00
15,CELL_016,0.02,0.040,🟢 HEALTHY (Stable),2024-01-02 08:18:00
3,CELL_004,0.01,0.024,🟢 HEALTHY (Stable),2024-01-02 09:23:00
12,CELL_013,0.00,0.024,🟢 HEALTHY (Stable),2024-01-02 09:00:00
19,CELL_020,0.02,0.013,🟢 HEALTHY (Stable),2024-01-02 09:20:00
14,CELL_015,0.00,0.013,🟢 HEALTHY (Stable),2024-01-02 08:20:00
6,CELL_007,0.00,0.008,🟢 HEALTHY (Stable),2024-01-02 08:58:00
7,CELL_008,0.00,0.002,🟢 HEALTHY (Stable),2024-01-02 09:21:00
10,CELL_011,0.00,0.001,🟢 HEALTHY (Stable),2024-01-02 08:37:00
17,CELL_018,0.00,0.001,🟢 HEALTHY (Stable),2024-01-02 09:08:00

# Threshold-Gated Switch

In [44]:
import numpy as np
import pandas as pd

# 1. Establish sorted dataframe and columns
node_column = (
    'cell_id'
    if 'cell_id' in master_telecom_df.columns
    else 'node_id'
    if 'node_id' in master_telecom_df.columns
    else master_telecom_df.columns[0]
)
time_column = (
    'timestamp'
    if 'timestamp' in master_telecom_df.columns
    else 'datetime'
    if 'datetime' in master_telecom_df.columns
    else None
)
failure_column = 'anomaly_flag'
history_window = 6

if time_column and time_column in master_telecom_df.columns:
  df_sorted = master_telecom_df.sort_values([node_column, time_column])
else:
  df_sorted = master_telecom_df.copy()

suffixes = ['_lag_1h', '_delta_1h', '_roll_std_3h', '_acceleration']
base_features = set()
for fc in feature_cols_forecast:
  base_col = fc
  for s in suffixes:
    if base_col.endswith(s):
      base_col = base_col[: -len(s)]
      break
  base_features.add(base_col)

# 2. Run Tiered Escalation Backtest
backtest_records = []
grouped = df_sorted.groupby(node_column)
print(f'Running tiered escalation backtest across {len(grouped)} nodes...\n')

for node_id, group in grouped:
  if len(group) < history_window + 5:
    continue

  for i in range(history_window, len(group)):
    window_df = group.iloc[i - history_window : i + 1].copy()

    for col in base_features:
      if col in window_df.columns and pd.api.types.is_numeric_dtype(
          window_df[col]
      ):
        window_df[f'{col}_lag_1h'] = window_df[col].shift(1)
        window_df[f'{col}_delta_1h'] = window_df[col] - window_df[
            f'{col}_lag_1h'
        ]
        window_df[f'{col}_roll_std_3h'] = window_df[
            col
        ].rolling(window=3).std()
        window_df[f'{col}_acceleration'] = window_df[f'{col}_delta_1h'] - (
            window_df[f'{col}_lag_1h'] - window_df[col].shift(2)
        )

    latest_row = window_df.iloc[[-1]]

    row_diag = (
        latest_row.reindex(columns=feature_cols_diag, fill_value=0)
        .select_dtypes(include=[np.number])
        .astype(float)
    )
    row_fore = (
        latest_row.reindex(columns=feature_cols_forecast, fill_value=0)
        .select_dtypes(include=[np.number])
        .astype(float)
    )

    if row_diag.isna().any().any() or row_fore.isna().any().any():
      continue

    try:
      diag_prob = float(rf_diag.predict_proba(row_diag)[:, 1][0])
      fore_prob = float(hgb_model.predict_proba(row_fore)[:, 1][0])
    except Exception:
      continue

    # Tiered Escalation Logic:
    # - CRITICAL: Active failure detected now (RF > 0.31)
    # - WARNING: 1-hour ahead early risk flagged by HGB (>= dynamic_thresh)
    is_critical = diag_prob > 0.31
    is_warning = fore_prob >= dynamic_thresh
    alert_triggered = is_critical or is_warning

    actual_failure = (
        int(latest_row[failure_column].values[0])
        if failure_column in latest_row.columns
        else 0
    )
    timestamp_val = (
        latest_row[time_column].values[0]
        if time_column in latest_row.columns
        else i
    )

    backtest_records.append({
        'node_id': node_id,
        'timestamp': timestamp_val,
        'diag_prob': round(diag_prob, 3),
        'fore_prob': round(fore_prob, 3),
        'alert_type': (
            '🔴 CRITICAL'
            if is_critical
            else '⚠️ WARNING'
            if is_warning
            else '🟢 HEALTHY'
        ),
        'alert_triggered': alert_triggered,
        'actual_failure': actual_failure,
    })

tier_df = pd.DataFrame(backtest_records)

# 3. Summarize Tiered Results
if not tier_df.empty:
  true_alerts = tier_df[
      (tier_df['alert_triggered']) & (tier_df['actual_failure'] == 1)
  ]
  false_alarms = tier_df[
      (tier_df['alert_triggered']) & (tier_df['actual_failure'] == 0)
  ]
  missed_failures = tier_df[
      (~tier_df['alert_triggered']) & (tier_df['actual_failure'] == 1)
  ]

  print('==================================================')
  print('     TIERED ESCALATION BACKTEST SUMMARY           ')
  print('==================================================')
  print(f'Total Snapshots Evaluated : {len(tier_df)}')
  print(f'True Early Warnings      : {len(true_alerts)}')
  print(f'False Alarms             : {len(false_alarms)}')
  print(f'Missed Failures          : {len(missed_failures)}')
  if (len(true_alerts) + len(false_alarms)) > 0:
    print(
        'Precision                :'
        f' {(len(true_alerts) / (len(true_alerts) + len(false_alarms)))*100:.2f}%'
    )
  print('==================================================')
  display(tier_df[tier_df['alert_triggered']].head(10))

Running tiered escalation backtest across 20 nodes...

==================================================
     TIERED ESCALATION BACKTEST SUMMARY
==================================================
Total Snapshots Evaluated : 1885
True Early Warnings      : 37
False Alarms             : 49
Missed Failures          : 2
Precision                : 43.02%
==================================================

,node_id,timestamp,diag_prob,fore_prob,alert_type,alert_triggered,actual_failure
1,CELL_001,2024-01-01 02:22:00,0.00,0.003,⚠️ WARNING,True,0
56,CELL_001,2024-01-01 15:19:00,0.70,0.001,🔴 CRITICAL,True,1
83,CELL_001,2024-01-02 01:58:00,0.00,0.003,⚠️ WARNING,True,0
103,CELL_001,2024-01-02 08:08:00,0.36,0.000,🔴 CRITICAL,True,1
175,CELL_002,2024-01-01 23:39:00,0.82,0.000,🔴 CRITICAL,True,1
198,CELL_002,2024-01-02 06:36:00,0.00,0.003,⚠️ WARNING,True,0
205,CELL_002,2024-01-02 09:02:00,0.34,0.000,🔴 CRITICAL,True,1
285,CELL_003,2024-01-01 23:48:00,0.74,0.000,🔴 CRITICAL,True,1
288,CELL_003,2024-01-02 00:42:00,0.80,0.000,🔴 CRITICAL,True,1
304,CELL_003,2024-01-02 06:39:00,0.00,0.003,⚠️ WARNING,True,0

#################################### DEMO #######################################

In [64]:
# --- Live Fleet Health Snapshot Dashboard ---
import pandas as pd


def render_noc_dashboard(tier_df):
  # Get the latest status snapshot for each unique node in the fleet
  latest_fleet_status = (
      tier_df.sort_values('timestamp')
      .groupby('node_id')
      .last()
      .reset_index()
  )

  # Select and rename columns for presentation
  dashboard_view = latest_fleet_status[[
      'node_id',
      'timestamp',
      'alert_type',
      'diag_prob',
      'fore_prob',
  ]].copy()
  dashboard_view.columns = [
      'Cell ID',
      'Timestamp',
      'Health Status',
      'Instant Risk (RF)',
      '1hr Forecast Risk (HGB)',
  ]

  # Sort by highest risk first
  dashboard_view = dashboard_view.sort_values(
      by='1hr Forecast Risk (HGB)', ascending=False
  )

  print('================================================================')
  print('            AMDOCS AIOPS: LIVE FLEET HEALTH MONITOR             ')
  print('================================================================')
  return dashboard_view


# Display the dashboard
display(render_noc_dashboard(tier_df))

================================================================
            AMDOCS AIOPS: LIVE FLEET HEALTH MONITOR
================================================================

,Cell ID,Timestamp,Health Status,Instant Risk (RF),1hr Forecast Risk (HGB)
0,CELL_001,2024-01-02 08:55:00,🟢 HEALTHY,0.00,0.001
12,CELL_013,2024-01-02 09:00:00,🟢 HEALTHY,0.00,0.001
18,CELL_019,2024-01-02 08:40:00,🟢 HEALTHY,0.00,0.001
3,CELL_004,2024-01-02 09:23:00,🟢 HEALTHY,0.01,0.001
17,CELL_018,2024-01-02 09:08:00,🟢 HEALTHY,0.00,0.001
8,CELL_009,2024-01-02 08:57:00,🟢 HEALTHY,0.01,0.001
13,CELL_014,2024-01-02 08:46:00,🟢 HEALTHY,0.00,0.001
1,CELL_002,2024-01-02 09:19:00,🟢 HEALTHY,0.01,0.001
16,CELL_017,2024-01-02 09:17:00,🟢 HEALTHY,0.00,0.000
15,CELL_016,2024-01-02 08:18:00,🟢 HEALTHY,0.02,0.000
14,CELL_015,2024-01-02 08:20:00,🟢 HEALTHY,0.00,0.000
10,CELL_011,2024-01-02 08:37:00,🟢 HEALTHY,0.00,0.000
11,CELL_012,2024-01-02 09:22:00,🟢 HEALTHY,0.00,0.000
9,CELL_010,2024-01-02 08:43:00,🟢 HEALTHY,0.04,0.000
7,CELL_008,2024-01-02 09:21:00,🟢 HEALTHY,0.00,0.000
6,CELL_007,2024-01-02 08:58:00,🟢 HEALTHY,0.00,0.000
5,CELL_006,2024-01-02 09:16:00,🟢 HEALTHY,0.00,0.000
4,CELL_005,2024-01-02 09:24:00,🟢 HEALTHY,0.00,0.000
2,CELL_003,2024-01-02 09:18:00,🟢 HEALTHY,0.00,0.000
19,CELL_020,2024-01-02 09:20:00,🟢 HEALTHY,0.02,0.000

In [60]:
# --- Dual-Mode Drill-Down: Auto-Find Success Story OR Type Custom Cell ID ---
import pandas as pd

# 1. Automatically find nodes with a True Early Warning
true_warning_nodes = tier_df[
    (tier_df['alert_triggered'] == True) & (tier_df['actual_failure'] == 1)
]['node_id'].unique()

# 👈 MANUAL OVERRIDE (Optional):
# Leave as None to let it auto-select a success story, OR type a specific cell ID string (e.g., 'cell_05')
manual_override_node = 'cell_001'

if manual_override_node and manual_override_node in tier_df['node_id'].values:
  demo_node = manual_override_node
  print(f'🎯 Using Manual Override Node: {demo_node}')
elif len(true_warning_nodes) > 0:
  demo_node = true_warning_nodes[0]
  print(
      '🔍 Auto-Selected True Early Warning Success Story of Node:'
      f' \033[1m{demo_node}\033[0m'
  )
else:
  demo_node = tier_df['node_id'].iloc[0]
  print(f'⚠️ No true warning node found. Defaulting to: {demo_node}')

# 2. Extract and display the timeline leading up to the event
node_timeline = tier_df[tier_df['node_id'] == demo_node].sort_values(
    'timestamp'
)

print(
    f'Showing telemetry timeline for \033[1m{demo_node}\033[0m (Last 10'
    ' recorded hours):\n'
)
display(
    node_timeline[[
        'timestamp',
        'diag_prob',
        'fore_prob',
        'alert_type',
        'actual_failure',
    ]].tail(10)
)

🔍 Auto-Selected True Early Warning Success Story of Node: CELL_001
Showing telemetry timeline for CELL_001 (Last 10 recorded hours):

               timestamp  diag_prob  fore_prob  alert_type  actual_failure
97   2024-01-02 05:42:00       0.00      0.000   🟢 HEALTHY               0
98   2024-01-02 05:53:00       0.00      0.001   🟢 HEALTHY               0
99   2024-01-02 06:16:00       0.00      0.000   🟢 HEALTHY               0
100  2024-01-02 06:19:00       0.01      0.000   🟢 HEALTHY               0
101  2024-01-02 06:24:00       0.00      0.000   🟢 HEALTHY               0
102  2024-01-02 07:43:00       0.00      0.000   🟢 HEALTHY               0
103  2024-01-02 08:08:00       0.36      0.000  🔴 CRITICAL               1
104  2024-01-02 08:16:00       0.01      0.001   🟢 HEALTHY               0
105  2024-01-02 08:50:00       0.00      0.001   🟢 HEALTHY               0
106  2024-01-02 08:55:00       0.00      0.001   🟢 HEALTHY               0

In [61]:
import json
import datetime


def trigger_remediation_webhook(node_id, alert_type, fore_prob):
  """Simulates dispatching an automated API payload or ticket

  when a predictive failure alert is confirmed.
  """
  payload = {
      'event_id': f'AIOPS-{int(datetime.datetime.now().timestamp())}',
      'timestamp': datetime.datetime.now().isoformat(),
      'target_node': node_id,
      'severity': (
          'HIGH' if 'CRITICAL' in alert_type else 'MEDIUM_PREDICTIVE'
      ),
      'alert_classification': alert_type,
      'forecast_risk_score': float(fore_prob),
      'recommended_action': (
          'AUTOMATED_TRAFFIC_OFFLOAD_AND_CONTAINER_REBOOT'
          if 'CRITICAL' in alert_type
          else 'PREVENTIVE_PRB_REALLOCATION'
      ),
      'integration_target': (
          'Amdocs_Smart_Net_Manager_API / ServiceNow_ITSM'
      ),
  }

  print('🚀 [ACTION LAYER TRIGGERED] Dispatched Automated Webhook Payload:')
  print(json.dumps(payload, indent=4))
  return payload


# Test the remediation trigger on your top risk node
if not tier_df.empty:
  sample_alert = tier_df[tier_df['alert_triggered']].iloc[0]
  trigger_remediation_webhook(
      sample_alert['node_id'],
      sample_alert['alert_type'],
      sample_alert['fore_prob'],
  )

🚀 [ACTION LAYER TRIGGERED] Dispatched Automated Webhook Payload:
{
    "event_id": "AIOPS-1790691135",
    "timestamp": "2026-09-29T16:12:15.239670",
    "target_node": "CELL_001",
    "severity": "MEDIUM_PREDICTIVE",
    "alert_classification": "\u26a0\ufe0f WARNING",
    "forecast_risk_score": 0.003,
    "recommended_action": "PREVENTIVE_PRB_REALLOCATION",
    "integration_target": "Amdocs_Smart_Net_Manager_API / ServiceNow_ITSM"
}